### PR TITLE
added support for x86_64 systems

### PR DESCRIPTION
**Pull request by asit-dhal**
updated for new GitHub location of Common API, and new pathnames

### CODE REVIEW

**Comment by gunnarx** [comment]
Thanks @asit-dhal I've been cleaning this up a bit (remove the Merge commits).  As it stands now those are just noise and none of the comments actually describe the changes that were made. 
But I ran out of time.  Will try to push a cleaned up update of this and merge it soon. Thanks again.

**Comment by gunnarx** [comment]
The update is done but I basically got stuck on the client program crashing when it runs...  I've seen some other reports but it could be something like a version mismatch possibly.

**Comment by gunnarx** [comment]
@asit-dhal Note - when you create a PR starting from your **master** branch it means I can update that PR (in other words push to your **master** branch).  I don't know if you really want that.  I usually try to push updates to the PR before merging because it will show that your contribution was merged on GitHub.
Let me know if it's OK, or if you want to recreate the PR.

**Comment by asit-dhal** [comment]
Hi gunnarx,

It's okay if you update that PR, I won't have any issue.

Thanks a lot.

**Comment by asit-dhal** [comment]
Hi Gunnarx,

I will close this PR and request another PR. The new PR will have better comments.

**Pull request closed without merging**
